### ISSUE TITLE
Build fails with react-native-webpack-server

### ISSUE THREAD

**Issue by license2e** [650Industries/react-native-invertible-scroll-view#15]
```
ERROR in ./~/react-native-invertible-scroll-view/~/react-native-clone-referenced-element/cloneReferencedElement.js
Module build failed: SyntaxError: /path/to/custom-react-native-app/node_modules/react-native-invertible-scroll-view/node_modules/react-native-clone-referenced-element/cloneReferencedElement.js: Unexpected token (18:6)
  16 |         'is not a function. Use a composable callback-style ref instead. ' +
  17 |         'Ignoring ref: ' + originalRef,
> 18 |       );
     |       ^
  19 |     }
  20 |     return React.cloneElement(element, config, ...children);
  21 |   }
    at Parser.pp.raise (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseExprAtom (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:425:12)
    at Parser.parseExprAtom (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExprListItem (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:801:16)
    at Parser.parseExprListItem (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:780:24)
    at Parser.pp.parseExprList (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:789:20)
    at Parser.pp.parseSubscripts (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/path/to/custom-react-native-app/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
 @ ./~/react-native-invertible-scroll-view/InvertibleScrollView.js 15:29-77
webpack: bundle is now VALID.
```

trailing comma in line 17 is causing the issue..

**Comment by ide** [comment]
Make sure your Babel config has ES7 trailing commas on.
